# Generated by Django 2.2.6 on 2021-08-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210803_1231'),
        ('posts', '0004_auto_20210803_1950'),
    ]

    operations = [
    ]
